### ISSUE TITLE
Light not working when running on raspberry pi

### ISSUE THREAD

**Issue by Th3M1k3y** [bitbyt3r/dmx#3]
I got one of those cheap modules, and tried to connect it to a raspberry pi 3b. I see the light on the board flashing, but the dmx light isnt responding. The light just blinks with the display, as if there isnt any valid dmx signal coming in.

To check if the dmx module worked, I tried the kmtronic.com DMX Tester on Windows 10, and it worked fine.

Heading back to the raspberry pi, and I again can't get it to work. Using the test.py file to test.

**Comment by bitbyt3r** [comment]
Do you have any details (or photos) of how it is wired? Do you have an oscilloscope to check the output?

**Comment by Th3M1k3y** [comment]
I do not have an oscilloscope. I haven't taken a picture of it, and it wouldn't show much either. It is 3 wires disappearing into a shielded 3 wire dmx cable, with an XLR connector on the other end.

I assume the wiring is correct, as it works fine when I use the test tool under windows, and also works in OLA.

Between the pi and the dmx module, there is just a 30cm usb cable.

**Comment by bitbyt3r** [comment]
I can try getting this working on a raspberry pi tonight. If it works I can try sending you an image to put on your SD card to see if that works.

**Comment by Th3M1k3y** [comment]
Thank you, that would be awesome. :)

**Comment by Th3M1k3y** [comment]
I did some more tests. I found a cheap oscilloscope (veeeeery cheap diy kit thing), and I can see pulses coming out of the dmx module.

I also tried to attach it to a powered usb hub, but still no success.

**Comment by bitbyt3r** [comment]
I was actually just working on putting an image together for you. I verified that it is working for my devices. If you can post a photo of what you are seeing on the oscilloscope I can try to verify the timing.

**Comment by Th3M1k3y** [comment]
![2019-10-03 20 49 47](https://user-images.githubusercontent.com/29869794/66155253-7e5e6180-e61f-11e9-80bd-72d4fc598f18.jpg)
Not sure if this is actually good enough to even do that... but this is what I got

**Comment by Th3M1k3y** [comment]
![2019-10-03 20 58 15](https://user-images.githubusercontent.com/29869794/66155733-94205680-e620-11e9-9f93-c9a3befaad19.jpg)
I just remembered, my pokit got oscilloscope function too. Lines on this is a bit thinner, so might be easier to see.

**Comment by Th3M1k3y** [comment]
Also, should the voltage not be from -2.5 to 2.5?

**Comment by bitbyt3r** [comment]
Here is a google drive link for a test image. This image will start test.py on boot, and is working with my setup: https://drive.google.com/file/d/1VoCJPo1Idt3RpIf3XQrq-4K3cByXYB1q/view?usp=sharing

**Comment by bitbyt3r** [comment]
If I remember correctly the voltage needs to stay between +/- 6v, and needs to cross at least 0.2v past the zero line on either side, so +/- 2.5v should be sufficient.
![eia485-voltage-switching-range](https://user-images.githubusercontent.com/1031406/66156147-1e4fc700-e5ef-11e9-8a38-1754ab45bcaf.png)

**Comment by Th3M1k3y** [comment]
Your image is working, now I wonder why the one I made isn't. Looking at the image from the oscilloscope, yours is also looking way different than mine.
![2019-10-03 21 09 37](https://user-images.githubusercontent.com/29869794/66156590-3bea5400-e622-11e9-9cc1-9ced646577a1.jpg)

**Comment by bitbyt3r** [comment]
I'm glad that is working! What were you doing on the python side of things when it wasn't working?

**Comment by Th3M1k3y** [comment]
All I got to, was to try the test script. I ran the two commands to install pyserial and your dmx generating script, and then started the test.py

Comparing the files I used and the ones you used, I also see no difference...

You havent changed any usb settings or something in this working image?

**Comment by bitbyt3r** [comment]
No, all I did to create the image was grab the latest raspbian lite, apt update/apt upgrade, install git/python3-virtualenv, clone this repo, install it into the venv, then create a systemd service manifest to start it on boot.

**Comment by Th3M1k3y** [comment]
Hmm, something is different. When I tried to run the script, I could just do `python test.py` and then it started to run. When I do that in your image, it complain about missing the serial module.

Instead I have to do `/home/pi/venv/bin/python test.py`

**Comment by bitbyt3r** [comment]
I installed everything into the virtual environment. It isn't good practice to install python packages into the system path, as that is managed by apt, which isn't aware of the changes made by pip. If you want `python test.py` to work then you can run `source /home/pi/venv/bin/activate`, which will add the venv to your python path and switch to the interpreter in the venv.

I'm going to close this issue since it sounds like things should be working now, but feel free to comment if you have questions/comments.

**Comment by bitbyt3r** [comment]
Oh, I did change one other thing on that image -- I disabled the filesystem resize so that it would be easier to zip up after the fact. If you want to use the whole SD card you can use raspi-config to resize the filesystem. Otherwise there is only a little free space left on the image.

**Comment by Th3M1k3y** [comment]
I will try to play around with it a bit more. When I know a bit more about it, I will then try to see if I can send the signal to the chip directly from the gpio. It should be possible when disabling the use of it from raspi-config. When I got that working, I will then design a PCB for it, along with some other things on the same PCB.
I want to have some sensor inputs, maybe some relay outputs too.

Thank you for your help. It all works as it should, I just have no idea what I did wrong when I tried the first time.

**Comment by bitbyt3r** [comment]
If you are designing a PCB it may be worth it to drop on a microcontroller to buffer the timings for you. You will need a line driver either way due to the negative voltages used in signalling.

**Comment by Th3M1k3y** [comment]
I did consider adding a microcontroller too, but the tests I have done weren't that great.

For the driver I just wanted to use the MAX485, it seems pretty easy to work with.

**Comment by Th3M1k3y** [comment]
I think I tried to use this last time I was testing having a microcontroller in between.

https://github.com/DaAwesomeP/dmxusb

With that on, it was possible to use same code for both the Enttec DMX Pro adapters and the microcontroller version.
